# top level stuff you probably don't need to touch
highlighter: pygments
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true


# edit here to achieve your personal greatness
url: http://tomstoneberg.com/
title: Tom Stoneberg
author: Tom Stoneberg
description: Personal website and resume of Tom Stoneberg
avatar: profile.png
email: tstoneb@gmail.com
github: stoneyb
twitter: tstoneb
#Comment out if you don't want disqus 
#disqus: username
google_analytics: UA-71946444-1 


# needed for travis-ci build
exclude: [vendor]
